<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
  * Implements hook_entity_field_access().
  */
function editor_can_publish_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  if ($field_definition->getname() == 'status') {
    if ($items != NULL) {
      $entity = $items->getEntity();
      if ($entity->getEntityTypeId() == 'node') {
        if ($account->hasPermission('edit any ' . $entity->bundle() . ' content')) {
          return AccessResult::allowed();
        }
        if ($entity->getOwnerId() == $account->id() && $account->hasPermission('edit own ' . $entity->bundle() . ' content')) {
          return AccessResult::allowed();
        }
      }
    }
  }
  return AccessResult::neutral();
}
